AT-1838 apparently netcat treads where ping fears to tread

diff --git a/.gitlab/ci/.jobs.yaml b/.gitlab/ci/.jobs.yaml
--- a/.gitlab/ci/.jobs.yaml
+++ b/.gitlab/ci/.jobs.yaml
@@ -8,7 +8,7 @@
     - |
       if [ "$HW_IN_THE_LOOP" == "true" ]; then
         # apt-get update && apt-get install iputils-ping netcat -y
-        ping -c 1 $PDU_IP || (echo "Cannot reach PDU" && exit 1) #FIXME: This is the type of config data that we should ideally be putting in Vault / Config database
+        ping -c 1 $PDU_IP || (echo "Cannot reach PDU") #FIXME: This is the type of config data that we should ideally be putting in Vault / Config database
         nc -zv $PDU_IP 22 || (echo "Cannot reach PDU SSH interface - go to  https://za-itf-pdu3.ad.skatelescope.org and reset" && exit 1)
       fi
     - bash .make/resources/gitlab_section.sh poetry "Install Python dependencies" poetry install
